name: docker CI
on: 
  push: 
    branches: 
      - main
    tags:
      - 'v**'
  pull_request:
    branches:
      - main
    tags:
      - 'v**'
  workflow_dispatch:
env:
  TAG_NAME: ${{ github.ref_name }}
  REGISTRY: ghcr.io
  DOCKER_USER: ${{ github.actor }}
  DOCKER_PWD: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: lower case IMAGE_NAME
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: build rust
        run: cargo build --release --verbose
      - name: Login to docker registry
        run: docker login -u $DOCKER_USER -p $DOCKER_PWD $REGISTRY
      - name: build images
        run: docker build . --file Dockerfile --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME
      - name: publish docker images
        run: docker push $REGISTRY/$IMAGE_NAME:$TAG_NAME
      - name: publish latest tag
        run: |
          docker tag $REGISTRY/$IMAGE_NAME:$TAG_NAME $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:latest
          
